---
author: "Vlad (+ Peter)"
date: "`r format(Sys.time(), '%a %Y-%b-%d')`"
output:
  github_document:
    toc: true
    toc_depth: 2
title: "Cooking UMCCR Genes"
editor_options:
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(stringi)
```

## Read in gene lists

### AZ300, PCGR Predispose, PMCC etc.
```{r lists}
# umccr_arthur <- read_tsv(str_c(folder, "sources/umccr_cancer_genes.20181112.txt"), col_names = c('symbol', 'sources'))
# genes <- umccr %>%
#   separate_rows(sources, sep = "\\|") %>%
#   filter(sources != 'AZ800') %>%
#   bind_rows(az300 %>% mutate(sources = "AZ300"))

read_genes <- function(x) {
  readr::read_tsv(x, col_names = 'symbol', col_types = 'c')
}

folder <- "../key_genes/sources"

sources <- c(predispose = "pcgr_predispose_genes.txt",
             az300 = "az_key_genes.300.txt",
             cacao = "cacao.txt",
             umccr = "umccr.txt")
panels_arthur <- c("PMCC", "TS500", "TEMPUS", "familial_cancer")

# 518
genes1 <- purrr::map(file.path(folder, sources), read_genes) %>%
  purrr::set_names(names(sources)) %>%
  dplyr::bind_rows(.id = "sources")

# 1647
genes2 <- purrr::map(file.path(folder, "arthur", paste0(panels_arthur, ".genes")), read_genes) %>%
  purrr::set_names(panels_arthur) %>%
  dplyr::bind_rows(.id = "sources")

# 2165 (= 1,647 + 518)
genes <- dplyr::bind_rows(genes1, genes2)
rm(genes1, genes2)
table(genes$sources, useNA = 'ifany') %>% addmargins()
```

### NCG - Network of Cancer Genes

```{r ncg}
# http://ncg.kcl.ac.uk/

# 711
ncg_tsgonco  <- readr::read_tsv(file.path(folder, "NCG6_tsgoncogene.tsv"))
# 2,876 (= 711 + 2,165)
genes_ncg <- genes %>%
  dplyr::bind_rows(ncg_tsgonco %>%
                     dplyr::mutate(sources = "ncg_known",
                                   ncg_og = NCG6_oncogene == 1,
                                   ncg_ts = NCG6_tsg == 1,
                                   ncg_fu = stringr::str_detect(cgc_annotation, "fusion")) %>%
                     dplyr::select(symbol, sources, starts_with("ncg_"))
  )

# 6,536
ncg_cancer <- readr::read_tsv(file.path(folder, "NCG6_cancergenes.tsv"))

# 374
ncg_cancer_other <- ncg_cancer %>%
  dplyr::filter(type != "Known Cancer") %>%
  dplyr::group_by(symbol) %>%
  dplyr::summarise(
    ncg_n = dplyr::n(),
    type = str_c(unique(type), collapse = ", "),
    cancer_type = str_c(unique(cancer_type), collapse = ", "),
    primary_site = str_c(unique(primary_site), collapse = ", "),
    method = str_c(unique(method), collapse = ", ")) %>%
  dplyr::arrange(desc(ncg_n)) %>%
  dplyr::filter(ncg_n >= 3)

# 3,250 (= 2,876 + 374)
genes_ncg <- genes_ncg %>%
  dplyr::bind_rows(ncg_cancer_other %>%
                     dplyr::mutate(sources = "ncg_other") %>%
                     dplyr::select(symbol, sources, ncg_n))

genes_ncg %>% filter(sources == "ncg_known") # 711
```

```{r cancermine}
# 15,781
cancermine <- readr::read_tsv(file.path(folder, "cancermine_collated.tsv"))

# 280
cancermine_prep <- cancermine %>%
  dplyr::mutate(symbol = gene_normalized,
                cm_cite = citation_count,
                cm_og = role == "Oncogene",
                cm_ts = role == "Tumor_Suppressor",
                cm_driver = role == "Driver") %>%
  dplyr::filter(citation_count >= 3 | symbol == "SMURF1") %>%
  dplyr::select(symbol, starts_with("cm_")) %>%
  dplyr::group_by(symbol) %>%
  dplyr::summarise(sources = "cancermine",
                   cm_pub = dplyr::n(),
                   cm_total_cite = sum(cm_cite),
                   cm_og = mean(cm_og),
                   cm_ts = mean(cm_ts),
                   cm_driver = mean(cm_driver)) %>%
  dplyr::filter(cm_pub >= 2)
# cancermine_prep %>% arrange(cm_pub, cm_total_cite)

# 3,530 (= 3,250 + 280)
genes_cm <- genes_ncg %>%
  dplyr::bind_rows(cancermine_prep)

genes_cm %>% dplyr::filter(sources == "cancermine") # 280
```

```{r oncokb}
# 1,019
oncokb <- readr::read_tsv(file.path(folder, "oncoKB_cancerGeneList.txt"))
# 2,486
oncokb_prep <- oncokb %>%
  dplyr::transmute(
    symbol = `Hugo Symbol`,
    oncokb = ifelse(`OncoKB Annotated` == "Yes", T, F),
    msk_impact = ifelse(`MSK-IMPACT` == "Yes", T, F),
    msk_heme = ifelse(`MSK-HEME` == "Yes", T, F),
    foundation_one = ifelse(`FOUNDATION ONE` == "Yes", T, F),
    foundation_one_heme = ifelse(`FOUNDATION ONE HEME` == "Yes", T, F),
    vogelstein = ifelse(`Vogelstein` == "Yes", T, F)
  ) %>%
  gather(key = "sources", value = "yes", -symbol) %>%
  filter(yes) %>%
  dplyr::select(-yes)

# 579
oncokb_prep %>% dplyr::filter(sources == "oncokb")

# 6,016
genes_ok <- genes_cm %>% dplyr::bind_rows(oncokb_prep)
```

```{r cosmic}
# 723
cosmic <-
  readr::read_tsv(file.path(folder, "CancerGeneCensus_Tier1.tsv")) %>%
  dplyr::bind_rows(
    readr::read_tsv(file.path(folder, "CancerGeneCensus_Tier2.tsv")))

# 723
cosmic_prep <- cosmic %>%
  dplyr::transmute(
    symbol = `Gene Symbol`,
    sources = ifelse(Tier == 1, 'cosmic1', 'cosmic2'),
    cos_germ = Germline == "yes",
    cos_ts = `Role in Cancer` == 'TSG',
    cos_og = `Role in Cancer` == 'oncogene',
    cos_fu = `Role in Cancer` == 'fusion')

# 6,739 (= 6,016 + 723)
genes_cos <- bind_rows(genes_ok, cosmic_prep)
# 723
genes_cos %>% filter(str_detect(sources, "cosmic"))
genes_cos %>% filter(grepl("cosmic", sources))
```

```{r tsg}
# 320
tsgene_ts <- read_genes(file.path(folder, "arthur/TSGene2-oncogenes.genes"))
# 1,217
tsgene_og <- read_genes(file.path(folder, "arthur/TSGene2-tumour-suppressors.genes"))

# 6,739
genes_tsg <- genes_cos %>%
  dplyr::mutate(
    tsg_ts = symbol %in% tsgene_ts,
    tsg_og = symbol %in% tsgene_og)
```

```{r hmf_fusions}
hmf_pairs <- readr::read_csv("../fusions/hmf_knownFusionPairs.csv")
hmf_prom_head <- readr::read_csv("../fusions/hmf_knownPromiscuousFive.csv", quote = '"')
hmf_prom_tail <- readr::read_csv("../fusions/hmf_knownPromiscuousThree.csv", quote = '"')

# 426
hmf_fus_genes <-
  dplyr::union_all(
    hmf_pairs %>% dplyr::select(symbol = threeGene),
    hmf_pairs %>% dplyr::select(symbol = fiveGene),
    hmf_prom_head %>% dplyr::select(symbol = gene),
    hmf_prom_tail %>% dplyr::select(symbol = gene)) %>%
  dplyr::distinct() %>% # union() combines union_all + distinct
  dplyr::mutate(sources = 'hmf', hmf_fu = T)

# 7,165 (= 6,739 + 426)
genes_hmf <- dplyr::bind_rows(genes_tsg, hmf_fus_genes)
```

```{r summarise}
# 1,733
genes_sum <- genes_hmf %>%
  dplyr::group_by(symbol) %>%
  dplyr::summarise(
    n = dplyr::n(),
    sources = str_c(sources, collapse = "|"),
    ncg = str_detect(sources, "ncg_known"),
    cosm1 = str_detect(sources, "cosmic1"),
    cancermine = str_detect(sources, "cancermine"),
    cacao = str_detect(sources, "cacao"),
    umccr = str_detect(sources, "umccr"),
    germ = any(cos_germ, na.rm = T) | str_detect(sources, "predispose"),
    
    ncg_ts = any(ncg_ts, na.rm = T),
    cm_ts = sum(cm_ts, na.rm = T),
    cos_ts = any(cos_ts, na.rm = T),
    tsg_ts = any(tsg_ts, na.rm = T),

    ncg_og = any(ncg_og, na.rm = T),
    cm_og = sum(cm_og, na.rm = T),
    cos_og = any(cos_og, na.rm = T),
    tsg_og = any(tsg_og, na.rm = T),

    driver = sum(cm_driver, na.rm = T),
    cos_fu = any(cos_fu, na.rm = T),
    hmf_fu = any(hmf_fu, na.rm = T),
    ncg_fu = any(ncg_fu, na.rm = T)
  ) %>%
  dplyr::mutate(
    tumorsuppressor = ncg_ts | cm_ts > 0 | cos_ts | tsg_ts,
    oncogene = ncg_og | cm_og > 0 | cos_og | tsg_og,
    fusion = hmf_fu | cos_fu | ncg_fu
  ) %>%
  dplyr::mutate(
    tier1 = ncg | cosm1 | cancermine | cacao | umccr | driver | n >= 4,  # well curated cancer genes
    key = tier1 | germ | n >= 2       # + not so confident + predisposition + known fusions
  ) %>%
  dplyr::select(-ends_with("_og"), -ends_with("_ts"), -starts_with("ncg_"))

genes_hmf %>% filter(symbol %>% str_detect("SMU"))
```

```{r compare_to_previous}
# 1,248
prev <- readr::read_tsv("../key_genes/umccr_cancer_genes.2019-03-20.tsv")
added   <- genes_sum %>% dplyr::filter(key, !symbol %in% prev$symbol)
added # 3: ABCB1, ASNS, MACF1
removed <- genes_sum %>% dplyr::filter(symbol %in% prev$symbol, !key)
removed # 2: DUX4L1, IL6R

genes_sum %>%
  dplyr::filter(key) %>% # 1,249
  dplyr::filter(tier1) # 994

genes_sum %>%
  dplyr::filter(key) %>%
  dplyr::filter(cosm1 & cancermine & !ncg)  # 0

genes_sum %>%
  dplyr::filter(key) %>%
  dplyr::filter(ncg) %>% # 711
  dplyr::arrange(desc(n))
genes_sum %>%
  dplyr::filter(key & !tumorsuppressor & !oncogene & !fusion & !germ) %>%
  dplyr::arrange(desc(n)) # 357
genes_sum %>% dplyr::filter(cos_fu & !hmf_fu) # 46
```

```{r write_results}
tsv_fp <- str_c("umccr_cancer_genes.", lubridate::today(), ".tsv", sep = "")
# 1,249
genes_sum %>%
  dplyr::filter(key) %>%
  dplyr::select(-key) %>%
  readr::write_tsv(file.path("../key_genes", tsv_fp))

list_fp <- str_c("umccr_cancer_genes.", lubridate::today(), ".genes", sep = "")
# just write gene names
genes_sum %>%
  dplyr::filter(key) %>%
  dplyr::pull(symbol) %>%
  readr::write_lines(file.path("../key_genes", list_fp))

tsgenes_fp <- str_c("umccr_cancer_genes.tsgenes.", lubridate::today(), ".genes", sep = "")
# 346
genes_sum %>%
  dplyr::filter(tumorsuppressor) %>%
  dplyr::pull(symbol) %>%
  readr::write_lines(file.path("../key_genes", tsgenes_fp))
```



```{r compare_to_arthurs_list}
added <- genes_sum %>% filter(keep, !symbol %in% umccr$symbol)
removed <- genes_sum %>% filter(symbol %in% umccr$symbol, !keep)

predispose %>% mutate(
  umccr = symbol %in% genes_sum$symbol
)

# # exlore sources of added genes
# genes4 %>% filter(symbol %in% added$symbol) %>% arrange(symbol)
#
# # exlore sources of removed genes
# genes4 %>% filter(symbol %in% removed$symbol) %>% arrange(symbol)
added
removed

genes_sum %>% filter(str_detect(sources, "AZ300")) %>% select(symbol, n, keep) %>% count(keep)

umccr %>% nrow()
genes_sum %>% filter(keep) %>% nrow()
```

Comparing COSMIC germline and PCGR predispose: PCGR includes _all_ COSMIC germline genes
```{r germline}
genes_tsg %>%
  group_by(symbol) %>%
  summarise(
    cos_germ = any(cos_germ, na.rm = T),
    predispose = any(str_detect(sources, "predispose"))
  ) %>% count(cos_germ, predispose)
```

```{r}
genes_sum %>%
  filter(symbol == "MYC") %>%
  select(-tsg_ts, -tsg_og, -cm_driver)
```
```{r}
  # group_by(symbol) %>%
  # summarise(
  #   n = dplyr::n(),
  #   cm_ts = str_c(cm_ts),
  #   cm_og = str_c(cm_og),
  #   ncg_og = ncg_og,
  #   ncg_ts = ncg_ts,
  #   ncg_fu = ncg_fu)

# Selecing:
# - Cancermine (we pre-selected at least 2 publications with at least 3 citations)
# - ncg_known
# - CancerGeneCensus_Tier1
# - At least in 2 of of clinical panels: MSKC-IMPACT, MSKC-HEME, PMCC, TS500, TEMPUS, FoundationONE, FoundationHEME
# - At least 2 sources from CancerGeneCensus_Tier2, AZ300, OncoKB-Annotated, FamilialCancer, Oncogenes, TumourSuppressors
genes4 %>% count(sources, sort = T)
# Annotating:
# - oncogene if ncg_og or mc_og >= 0.1
# - tumor_suppressor if ncg_ts or cm_ts >= 0.1
# - fusion if ncg_fu
genes4 %>% count(ncg_ts)
# The result is a list of 1387 genes:
#   - 1114 genes in at least one clinical panel
#   - 194 genes in database that are not in any of used clinical panel
#   - 79 genes in ensemble (2+) lists that are not included above

# | any(cm_og, na.rm = T) | any(cm_og, na.rm = T))
```

```{r}
genes_sum %>% count(cm_ts > 0, ncg_ts, tsg_ts)
genes_sum %>% filter(cm_ts > 0, ncg_ts, tsg_ts)
genes_sum %>% count(cm_og > 0, ncg_og, tsg_og)
genes_sum %>% filter(symbol == 'BRCA1')
```

```{r}
cancermine_oncogene <- cancermine %>% filter(role == "Oncogene")
ncg_oncogene <- ncg_tsgonco %>% filter(NCG6_oncogene == 1)
cancermine_oncogene
ncg_oncogene
```

```{r}
ncg_cancer$symbol %>% unique() %>% length()
```

```{r}
ncg_tsgonco$symbol %>% unique() %>% length()
```

```{r}
dplyr::intersect(umccr, unique(ncg_cancer$symbol)) %>% unique() %>% length()
```
```{r}
dplyr::intersect(umccr, ncg_tsgonco$symbol %>% unique()) %>% unique() %>% length()
```
```{r}
dplyr::setdiff(unique(ncg_tsgonco$symbol), umccr) %>% unique()
```

```{r}
ncg_cancer_collapsed <- ncg_cancer %>%
  group_by(symbol) %>%
  summarise(
    n = dplyr::n(),
    type = str_c(unique(type), collapse=", "),
    cancer_type = str_c(unique(cancer_type), collapse=", "),
    primary_site = str_c(unique(primary_site), collapse=", "),
    method = str_c(unique(method), collapse=", ")
  )

ncg_cancer_collapsed %>% filter(symbol %in% umccr) %>% arrange(desc(n)) %>% filter(n <= 8)
```


```{r}
ncg_cancer %>% filter(symbol == "MKL1")
```
